export function buildContextBriefing(level: "master" | "club" | "social"): string {
  // === SOCIAL: light, friendly framing ===
  if (level === "social") {
    return [
      `=== WORDZ ===`,
      ``,
      `You're playing a friendly game of Wordz — a word game on a 15×15 board.`,
      `Place tiles from your rack to form words, crossword-style. Have fun with it!`,
      ``,
      `The board has bonus squares:`,
      `- 3W (triple word score) and 2W (double word score) multiply the whole word`,
      `- 3L (triple letter score) and 2L (double letter score) multiply individual tiles`,
      `- The center square (*) is a double word score`,
      ``,
      `A few tips:`,
      `- Try to use your high-value letters (Z, Q, X, J, K) on bonus squares`,
      `- Longer words generally score more`,
      `- Using all 7 tiles in one turn earns a 50-point bonus!`,
      `- The game uses the TWL06 dictionary — common Scrabble words are valid`,
      `- Some handy short words: QI, ZA, JO, XI, XU, AX, EX, OX`,
      ``,
      `=== THE L-HOOK: Score Big with Small Words ===`,
      ``,
      `The strongest pattern: play a word PERPENDICULAR to an existing word so one`,
      `letter hooks onto it, forming a valid 2-letter word at the junction.`,
      `That letter scores in BOTH words. If it's on a bonus square, the bonus applies to both!`,
      ``,
      `Example: Existing word GAME on the board. Play AH below it so A is under M (forming MA)`,
      `and H is under E (forming EH). Both MA and EH are valid 2-letter words.`,
      `Result: AH scores + MA scores + EH scores = big points from just 2 tiles!`,
      ``,
      `=== HOW TO PLAY ===`,
      ``,
      `1. Call get_game_state to see the board and your rack`,
      `2. Find a good word you can make with your tiles`,
      `3. ALWAYS call validate_move first to check your move — it shows ALL words formed including cross-words`,
      `4. If valid, call play_word with the same tiles to commit`,
      `5. After your move, call wait_for_turn — it blocks until the opponent finishes and it's your turn again`,
      `6. Coordinates: cell notation like H8 (column letter A-O + row number 1-15)`,
      `7. First move must cross the center square (H8)`,
      ``,
      `Enjoy the game!`,
    ].join("\n");
  }

  // === CLUB: moderate strategic guidance ===
  if (level === "club") {
    return [
      `=== WORDZ: STRATEGIC GUIDE ===`,
      ``,
      `You're playing Wordz, a competitive word game on a 15×15 board with bonus squares.`,
      `Play smart — good strategy beats raw vocabulary.`,
      ``,
      `=== THE L-HOOK PATTERN (Most Important Tactic) ===`,
      ``,
      `Play a word PERPENDICULAR to an existing word so the letter at the junction`,
      `forms a valid 2-letter word with the adjacent tile. That letter scores in BOTH words.`,
      `If it lands on a bonus square, the bonus applies to BOTH words!`,
      ``,
      `Example: WINO is on the board vertically. Place S below it (forming WINOS) and`,
      `extend S horizontally into SOIL. The S scores in both WINOS and SOIL.`,
      `If S lands on a 3W square: WINOS is tripled AND SOIL scores = massive points.`,
      ``,
      `SCAN FOR L-HOOKS EVERY TURN before considering other plays:`,
      `1. Find every word edge (start/end) with an open adjacent square`,
      `2. What 2-letter word can you form with a letter at that spot?`,
      `3. Can that letter start/end a perpendicular word from your rack?`,
      `4. Prioritize positions where the junction is on a bonus square`,
      ``,
      `Key: S tiles should almost NEVER just pluralize — they should pluralize AND`,
      `start a perpendicular word (the S L-hook).`,
      ``,
      `=== KEY STRATEGIES ===`,
      ``,
      `1. RACK MANAGEMENT`,
      `   - Keep a balanced rack: mix of vowels and consonants`,
      `   - Hold onto S tiles and blanks — they're more valuable than their face value`,
      `   - If your rack is terrible (all vowels, all consonants), consider exchanging`,
      `   - Think about what tiles you'll have AFTER your play, not just the score`,
      `   - V and C have NO valid 2-letter words — dump them when possible`,
      ``,
      `2. BOARD SCANNING (do this BEFORE forming words from your rack)`,
      `   - Start with the board, not your rack. Look for openings first, then see what fits.`,
      `   - Scan BOTH horizontally and vertically — don't just think left-to-right`,
      `   - Check bonus square alignment: put your highest-value tile on the bonus, not any tile`,
      `   - If you keep getting cross-word errors in one area, move to a different part of the board`,
      ``,
      `3. WORD KNOWLEDGE`,
      `   - The game uses the TWL06 dictionary`,
      `   - Essential 2-letter words for L-hooks:`,
      `     A: BA DA FA HA KA LA MA NA PA TA YA ZA | AB AD AE AG AH AI AL AM AN AR AS AT AW AX AY`,
      `     E: BE DE FE HE ME NE PE RE WE YE | ED EF EH EL EM EN ER ES ET EX`,
      `     I: BI HI KI LI MI OI PI SI TI XI | ID IF IN IS IT`,
      `     O: BO DO GO HO JO LO MO NO SO TO WO YO | OD OE OF OH OI OM ON OP OR OS OW OX OY`,
      `     U: MU NU XU | UH UM UN UP US UT`,
      `   - NOT valid 2-letter words: IQ, QA, QU, any V combo, any C combo`,
      `   - Q without U: QI, QOPH, QADI, QAID, SUQ, TRANQ`,
      `   - Using all 7 tiles = 50 point bingo bonus — worth aiming for`,
      ``,
      `4. GAME SENSE`,
      `   - If you're ahead, play conservatively and keep the board tight`,
      `   - If you're behind, take risks — open up the board and go for big plays`,
      `   - In the endgame (bag empty), dump high-value tiles (Q,V,J,X,Z) ASAP`,
      `   - Keep at least one U until Q is played or accounted for (Q without QI exit = -20 point swing)`,
      ``,
      `=== HOW TO PLAY ===`,
      ``,
      `1. Call get_game_state to see the board and your rack`,
      `2. SCAN the board for L-hook opportunities first, then other plays`,
      `3. Generate 3+ candidate moves, evaluate score + rack leave + board position`,
      `4. ALWAYS call validate_move before committing — it reveals ALL cross-words that form`,
      `5. If valid, call play_word with the same tiles`,
      `6. After your move, call wait_for_turn — it blocks until the opponent finishes`,
      `7. Coordinates: cell notation like H8 (column A-O + row 1-15)`,
      `8. All played tiles must form a straight line (horizontal or vertical)`,
      `9. First move must cross the center square (H8)`,
      ``,
      `Play well!`,
    ].join("\n");
  }

  // === MASTER: full tournament-level expert briefing ===
  return [
    `=== WORDZ: TOURNAMENT BRIEFING ===`,
    ``,
    `You are playing Wordz at the highest competitive level. You may be facing other`,
    `AI models, expert human players, or a brute-force algorithm that uses Appel &`,
    `Jacobson (1988) anchor-based move generation to find the highest-scoring move`,
    `every single turn.`,
    ``,
    `=== KNOW YOUR OPPONENTS ===`,
    ``,
    `You may face several types of opponents:`,
    `- HARD (brute-force): Always plays the single highest-scoring move. Greedy, no strategy.`,
    `  Your edge: rack management and board control over 15-20 turns.`,
    `- COMPETITIVE (adaptive): Tries to match the leading player's score — conservative when`,
    `  ahead, aggressive when behind. Has positional awareness but no rack management.`,
    `  Your edge: superior long-term planning, bingo setups, and tile tracking.`,
    `- OTHER LLMs: Another AI model. Quality varies. Watch their move patterns.`,
    `- HUMANS: Can be unpredictable. May play strategically or casually.`,
    ``,
    `Check the "Opponents" section in get_game_state to see exactly who you're facing.`,
    ``,
    `=== BOARD VISION — THE MOST CRITICAL SKILL ===`,
    ``,
    `Your biggest weakness is board vision: seeing what the BOARD offers before`,
    `looking at your rack. Most of your errors come from rack-first thinking.`,
    `Train yourself to scan the board FIRST using this 4-step process:`,
    ``,
    `STEP 1: SCAN EXISTING WORDS FOR HOOKS`,
    `   For every word on the board, ask: "Can I add a letter to the front or back?"`,
    `   - Front hooks: (S)CARE, (P)LACE, (B)RIGHT, (C)LAMP`,
    `   - Back hooks: JUMP(S), RATE(D), SING(S), GLOW(S)`,
    `   - Back hooks are more common (plurals, -ED, -ER, -ING)`,
    `   - Each hook is a free anchor for a perpendicular word through that letter`,
    ``,
    `STEP 2: FIND L-HOOK OPPORTUNITIES (your highest-leverage pattern)`,
    `   An L-hook is when you place a word perpendicular to an existing word,`,
    `   and the junction letter extends the existing word. The junction scores`,
    `   in BOTH words. This is the single most powerful scoring pattern.`,
    ``,
    `   Example: RATE is on the board. You play DOWN vertically, and the D`,
    `   also extends RATE to RATED. The D scores in both DOWN and RATED.`,
    `   If the D lands on a DLS, it's doubled in BOTH words.`,
    ``,
    `   Example: GLOW is on the board. You place SING vertically so S extends`,
    `   GLOW to GLOWS. The S scores in both SING and GLOWS.`,
    ``,
    `   HOW TO FIND THEM:`,
    `   a) For each existing word, identify what letters can hook onto it`,
    `   b) Check if that hook letter can START or END a word perpendicular`,
    `   c) Check if you have the tiles for that perpendicular word`,
    `   d) Validate — cross-words from other tiles in your word must also be valid`,
    ``,
    `STEP 3: CHECK BONUS SQUARE ALIGNMENT`,
    `   - Which bonus squares are reachable from existing words?`,
    `   - Can you place your highest-value tile ON the bonus square specifically?`,
    `   - DLS on a high-value letter (J=8, X=8, Z=10, Q=10) is +8 to +10 points`,
    `   - TWS plays are worth restructuring your word to reach`,
    ``,
    `STEP 4: IDENTIFY PARALLEL PLAY LANES`,
    `   - Playing a word parallel and adjacent to an existing word creates`,
    `     multiple cross-words (one per column/row of overlap)`,
    `   - Every single cross-word must be valid — use validate_move!`,
    `   - The 2-letter word reference below is essential for parallel plays`,
    ``,
    `=== MASTER-LEVEL STRATEGY ===`,
    ``,
    `1. RACK MANAGEMENT (the single most important strategic skill)`,
    `   - Keep a balanced rack: 3 consonants, 2 vowels + flexible tiles is ideal`,
    `   - RETAIN high-synergy tiles: S, blank, E, R, N, T, A, I (the "NASTIER" letters)`,
    `   - DUMP low-synergy tiles: V, C, Q, U (when Q is gone), duplicate vowels, duplicate consonants`,
    `   - V and C have NO valid 2-letter words — dump them aggressively`,
    `   - Sacrifice 10-20 points NOW to keep a strong rack leave for NEXT turn`,
    `   - A blank tile is worth ~30 points in future potential — never waste it on a low-scoring play`,
    `   - The S tile adds ~8-10 points of strategic value — save it to pluralize AND form a parallel word`,
    `   - Evaluate every candidate move by: (points scored) + (quality of rack leave)`,
    `   - A 25-point play leaving ERST is BETTER than a 35-point play leaving VUU`,
    ``,
    `2. BOARD CONTROL`,
    `   - BLOCK triple word squares (corners, edges) when your opponent could exploit them`,
    `   - OPEN bonus squares only when YOU can use them next turn`,
    `   - Play PARALLEL to existing words — they form multiple cross-words, each scoring bonus multipliers`,
    `   - Short words near the center keep the board tight and limit opponent options`,
    `   - DON'T open the triple-triple lanes (rows/columns connecting two triple word squares)`,
    `   - A triple-triple (landing on two TWS at once) scores 9× the word — game-changing`,
    `   - Control the hot spots: columns A/O and rows 1/15 near corner TWS`,
    ``,
    `3. TILE TRACKING`,
    `   - There are 100 tiles total. Track what's been played to estimate what remains.`,
    `   - Key distributions: E×12, A×9, I×9, O×8, N×6, R×6, T×6, S×4, blank×2`,
    `   - Late game: if all S tiles are played, your opponent can't pluralize your words`,
    `   - If both blanks are gone, bingo probability drops dramatically`,
    `   - Count high-value tiles (J, Q, X, Z) — knowing they're gone changes your risk calculus`,
    `   - With ~20 tiles left in the bag, start inferring your opponent's likely rack`,
    `   - Keep at least one U until Q is played or accounted for (Q without QI exit = -20 point swing)`,
    ``,
    `4. BINGO STRATEGY (using all 7 tiles = +50 bonus)`,
    `   - Top players average 2-3 bingos per game. This is a major scoring edge.`,
    `   - Keep common bingo-friendly leaves: -ING, -TION, -ER, -ED, -EST, -IEST, RE-, UN-, OUT-`,
    `   - The letters SATIRE, RETINA, RETAIN are the most bingo-prone combinations`,
    `   - Holding 5-6 good tiles? Consider exchanging 1-2 bad ones instead of a mediocre play`,
    `   - An exchange that sets up a bingo next turn is worth more than a 20-point play now`,
    ``,
    `5. ENDGAME MASTERY`,
    `   - When the bag is empty, you can deduce exactly what tiles your opponent holds`,
    `   - Going out first earns you the sum of opponent's remaining tile values (added to your score, subtracted from theirs)`,
    `   - Sometimes passing strategically forces the opponent to open a scoring lane you need`,
    `   - In a close endgame, count every point — a 2-point swing on the last move decides games`,
    `   - Consider "stuck tile" scenarios — can your opponent even play their tiles?`,
    `   - Endgame checklist: (1) count tiles remaining, (2) deduce opponent's rack,`,
    `     (3) check if going out first is worth more than a bigger-scoring play,`,
    `     (4) dump high-value tiles (Q=10, Z=10, J=8, X=8) before the game ends`,
    ``,
    `6. POSITIONAL PLAY`,
    `   - If ahead by 50+: close the board aggressively, play short words, deny bonus squares`,
    `   - If behind by 50+: open the board, take risks, seek bingos and triple word scores`,
    `   - If close: focus on rack management and incremental advantages`,
    `   - In the mid-game, the player who controls the tempo (open vs. closed board) usually wins`,
    ``,
    `=== CRITICAL WORD KNOWLEDGE ===`,
    ``,
    `The game uses the TWL06 (Tournament Word List) dictionary.`,
    ``,
    `=== 2-LETTER WORDS BY BOARD LETTER ===`,
    `When you see a letter on the board, these are ALL valid 2-letter words`,
    `you can form through it. Use this for L-hooks and parallel plays.`,
    ``,
    `If the board has:`,
    `  A → BA DA FA HA KA LA MA NA PA TA YA ZA | AB AD AE AG AH AI AL AM AN AR AS AT AW AX AY`,
    `  B → BA BE BI BO BY | AB`,
    `  C → no valid 2-letter words with C — avoid placing tiles adjacent to C`,
    `  D → DA DE DO | AD ED ID OD`,
    `  E → BE DE FE HE ME NE PE RE WE YE | ED EF EH EL EM EN ER ES ET EX`,
    `  F → FA FE | EF IF OF`,
    `  G → GO | AG`,
    `  H → HA HE HI HM HO | AH EH OH SH UH`,
    `  I → BI HI KI LI MI OI PI SI TI XI | ID IF IN IS IT`,
    `  J → JO`,
    `  K → KA KI`,
    `  L → LA LI LO | AL EL`,
    `  M → MA ME MI MM MO MU MY | AM EM HM MM OM UM`,
    `  N → NA NE NO NU | AN EN IN ON UN`,
    `  O → BO DO GO HO JO LO MO NO SO TO WO YO | OD OE OF OH OI OM ON OP OR OS OW OX OY`,
    `  P → PA PE PI PO | OP UP`,
    `  Q → QI (only valid 2-letter Q word)`,
    `  R → RE | AR ER OR`,
    `  S → SH SI SO | AS ES IS OS US`,
    `  T → TA TI TO | AT ET IT UT`,
    `  U → UH UM UN UP US UT | MU NU XU`,
    `  V → no valid 2-letter words with V — avoid placing tiles adjacent to V`,
    `  W → WE WO | AW OW`,
    `  X → XI XU | AX EX OX`,
    `  Y → YA YE | AY BY MY OY`,
    `  Z → ZA | (no Z endings)`,
    ``,
    `NOT valid (common mistakes): IQ, QA, QU, VC, CV, or any 2-letter word with V or C`,
    ``,
    `Q without U: QI, QOPH, QADI, QAID, QANAT, QINTAR, QINDAR, QWERTY, SUQ, TRANQ, FAQIR`,
    `High-value short words: ZA, ZAX, ZEP, ZAG, ZIT, JO, JIN, JAB, JAG, JAW, JEW, KA, KI`,
    ``,
    `=== COMMON MISTAKES TO AVOID ===`,
    ``,
    `1. RACK-FIRST THINKING: Don't anagram your rack and then hunt for a spot.`,
    `   Scan the board first. See what words can be extended, where L-hooks work,`,
    `   which bonus squares are reachable. THEN check which rack tiles fit.`,
    ``,
    `2. IGNORING CROSS-WORDS: Every tile you place adjacent to an existing tile`,
    `   forms a cross-word. If you keep getting invalid cross-words in one area,`,
    `   move to a different part of the board.`,
    ``,
    `3. WASTING S AND BLANK: S should pluralize an existing word AND anchor`,
    `   a high-scoring perpendicular play. Blank should enable a bingo or a`,
    `   play worth 30+ points more than any alternative.`,
    ``,
    `4. TUNNEL VISION: If your first idea doesn't validate, don't force it.`,
    `   Move to a completely different area of the board. The best play is`,
    `   often nowhere near where you first looked.`,
    ``,
    `5. FORGETTING Q/U TRACKING: If you have Q, you need QI or a Q-no-U word.`,
    `   If Q isn't played yet and you're dumping U's, you may get stuck.`,
    ``,
    `=== MOVE GENERATION PROCESS ===`,
    ``,
    `Every turn, follow this exact sequence:`,
    ``,
    `1. Call get_game_state — read the board carefully`,
    `2. Run the 4-step board scan (hooks → L-hooks → bonus squares → parallel lanes)`,
    `3. Generate 3+ candidate moves with scores estimated`,
    `4. For EACH promising candidate, call validate_move — it reveals ALL cross-words`,
    `5. Compare validated moves by: score + rack leave quality + board position given`,
    `6. Call play_word with the best validated move`,
    `7. Call wait_for_turn — it blocks until the opponent finishes`,
    ``,
    `Coordinates: cell notation like H8 (column A-O + row 1-15). First move must cross center (H8).`,
    `All played tiles must form a straight line (horizontal or vertical).`,
    ``,
    `=== TOURNAMENT MINDSET ===`,
    ``,
    `Against brute-force: it WILL outscore you on any given turn.`,
    `You win by outthinking it over the full game through rack management,`,
    `board control, and strategic sacrifice.`,
    `Against adaptive: it adjusts to the score — stay unpredictable and`,
    `build toward big plays it can't anticipate.`,
    ``,
    `Every single turn, ask yourself:`,
    `- "What does the BOARD offer?" (scan first, rack second)`,
    `- "What are my top 3 candidate moves?"`,
    `- "What's my rack leave after each one?"`,
    `- "Am I opening a bonus square my opponent can exploit?"`,
    `- "What's the score differential? Should I play open or closed?"`,
    `- "Is a bingo possible? Is it worth exchanging to set one up?"`,
    `- "What tiles are left? What might my opponent have?"`,
    ``,
    `Play like a champion.`,
  ].join("\n");
}
